const tea = [
    {
        type: 1,
        organic: false,
        color: '#e3dc65',
        name: 'Dragon Well',
        nameOther: 'Long Jing',
        season: '28th March 2017',
        cultivar: 'Xiao Ye',
        origin: 'Xinchang, Zhejiang, China',
        rating: 5,
        updated: '13/01/2018',
        link: 'https://meileaf.com/tea/imperial-green-pre-qing-ming/',
        brewing: {
            western: {
                temperature: 80,
                amount: 1,
                baseDuration: 120,
                durationIncrease: 60,
                infusions: 2,
            },
            gongfu: {
                temperature: 80,
                amount: 3.5,
                baseDuration: 20,
                durationIncrease: 15,
                infusions: 5,
            },
        },
    },
    {
        type: 2,
        organic: false,
        color: '#e7d373',
        name: 'White Hair Silver Needle',
        nameOther: 'Bai Hao Yin Zhen',
        season: '19th March 2017',
        cultivar: 'Da Bai',
        origin: 'Songyang, Zhejiang, China',
        rating: 5,
        updated: '13/01/2018',
        link: 'https://meileaf.com/tea/silver-needle/',
        brewing: {
            western: {
                temperature: 80,
                amount: 1,
                baseDuration: 180,
                durationIncrease: 30,
                infusions: 3,
            },
            gongfu: {
                temperature: 80,
                amount: 4,
                baseDuration: 60,
                durationIncrease: 30,
                infusions: 5,
            },
        },
    },
    {
        type: 1,
        organic: false,
        color: '#c9e539',
        name: 'Yame Gyokuro',
        nameOther: false,
        season: 'Shincha 2017',
        cultivar: 'Yabukita',
        origin: 'Yame, Fukuoka, Japan',
        rating: 5,
        updated: '13/01/2018',
        link: 'https://www.o-cha.com/yame-gyokuro.html',
        brewing: {
            gongfu: {
                temperature: 60,
                amount: 4.5,
                baseDuration: 120,
                durationIncrease: 30,
                infusions: 5,
            },
        },
    },
    {
        type: 1,
        organic: true,
        color: '#c5d941',
        name: 'Kanaya Midori Sencha',
        nameOther: false,
        season: 'Shincha 2017',
        cultivar: 'Kanaya Midori',
        origin: 'Kirishima, Kagoshima, Japan',
        rating: 5,
        updated: '13/01/2018',
        link: 'https://www.o-cha.com/fr/japanese-organic-sencha.html',
        brewing: {
            western: {
                temperature: 75,
                amount: 1,
                baseDuration: 120,
                durationIncrease: 20,
                infusions: 2,
            },
            gongfu: {
                temperature: 75,
                amount: 3.5,
                baseDuration: 60,
                durationIncrease: 10,
                infusions: 5,
            },
        },
    },
    {
        type: 4,
        organic: false,
        color: '#890008',
        name: 'Black Rose',
        nameOther: false,
        season: 'April 2017',
        cultivar: 'Zheng He',
        origin: 'Wuyi, Fujian, China',
        rating: 3,
        updated: '13/01/2018',
        link: 'https://meileaf.com/tea/black-rose/',
        brewing: {
            western: {
                temperature: 90,
                amount: 1,
                baseDuration: 120,
                durationIncrease: 60,
                infusions: 4,
            },
            gongfu: {
                temperature: 90,
                amount: 4.5,
                baseDuration: 10,
                durationIncrease: 5,
                infusions: 8,
            },
        },
    },
    {
        type: 4,
        organic: false,
        color: '#a81b00',
        name: 'Keemun',
        nameOther: 'Qimen Hao Ya',
        season: 'Spring 2017',
        cultivar: 'Zu Ye Zhong',
        origin: 'Mingzhou, Anhui, China',
        rating: 3,
        updated: '13/01/2018',
        link: 'https://meileaf.com/tea/superior-keemun/',
        brewing: {
            western: {
                temperature: 90,
                amount: 1,
                baseDuration: 120,
                durationIncrease: 60,
                infusions: 3,
            },
            gongfu: {
                temperature: 90,
                amount: 4.5,
                baseDuration: 10,
                durationIncrease: 5,
                infusions: 8,
            },
        },
    },
    {
        type: 3,
        organic: false,
        color: '#e4b34c',
        name: 'Jasmine Jade',
        nameOther: 'Mo Li Wulong',
        season: '28th April 2017',
        cultivar: 'Huang Dan',
        origin: 'Jingu, Fujian, China',
        rating: 4,
        updated: '13/01/2018',
        link: 'https://meileaf.com/tea/jasmine-jade-oolong/',
        brewing: {
            western: {
                temperature: 99,
                amount: 1,
                baseDuration: 120,
                durationIncrease: 30,
                infusions: 3,
            },
            gongfu: {
                temperature: 99,
                amount: 5,
                baseDuration: 20,
                durationIncrease: 10,
                infusions: 9,
            },
        },
    },
    {
        type: 6,
        organic: false,
        color: '#e0c159',
        name: 'White Blossom',
        nameOther: 'Jasmine Yin Zhen and Chrysanthemum',
        season: 'Various',
        cultivar: 'Various',
        origin: 'Various',
        rating: 3,
        updated: '13/01/2018',
        link: 'https://meileaf.com/tea/white-blossom/',
        brewing: {
            western: {
                temperature: 80,
                amount: 0.5,
                baseDuration: 180,
                durationIncrease: 30,
                infusions: 3,
            },
            gongfu: {
                temperature: 80,
                amount: 3.5,
                baseDuration: 30,
                durationIncrease: 10,
                infusions: 5,
            },
        },
    },
    {
        type: 2,
        organic: false,
        color: '#e4c93d',
        name: 'White Peony',
        nameOther: 'Bai Mu Dan',
        season: 'Spring 2016',
        cultivar: 'Da Bai',
        origin: 'Taimu, Fujian, China',
        rating: 5,
        updated: '13/01/2018',
        link: 'https://meileaf.com/tea/white-peony/',
        brewing: {
            western: {
                temperature: 85,
                amount: 0.5,
                baseDuration: 120,
                durationIncrease: 30,
                infusions: 5,
            },
            gongfu: {
                temperature: 85,
                amount: 3.5,
                baseDuration: 20,
                durationIncrease: 10,
                infusions: 7,
            },
        },
    },
    {
        type: 1,
        organic: false,
        color: '#e3de54',
        name: 'Cloud and Mist',
        nameOther: 'Yun Wu',
        season: '15th April 2017',
        cultivar: 'Xiao Ye',
        origin: 'Yu Yuan, Zhejiang, China',
        rating: 4,
        updated: '13/01/2018',
        link: 'https://meileaf.com/tea/cloud-lake/',
        brewing: {
            western: {
                temperature: 80,
                amount: 0.5,
                baseDuration: 120,
                durationIncrease: 30,
                infusions: 3,
            },
            gongfu: {
                temperature: 80,
                amount: 3.5,
                baseDuration: 10,
                durationIncrease: 5,
                infusions: 7,
            },
        },
    },
    {
        type: 7,
        organic: false,
        color: '#ece74b',
        name: 'Lotus Tea',
        nameOther: 'He Ye Cha',
        season: false,
        cultivar: 'Folium Nelumbinis',
        origin: 'Henan, China',
        rating: 5,
        updated: '13/01/2018',
        link: 'https://innatureteas.com/shop/lotus-tea/lotus-tea',
        brewing: {
            gongfu: {
                temperature: 90,
                amount: 3,
                baseDuration: 120,
                durationIncrease: 30,
                infusions: 5,
            },
        },
    },
    {
        type: 1,
        organic: false,
        color: '#f2dc6d',
        name: 'Green Snail Spring',
        nameOther: 'Bi Luo Chun',
        season: '27th March 2017',
        cultivar: 'Dong Ting Qunti',
        origin: 'Dong Ting, Jiangsu, China',
        rating: 5,
        updated: '14/01/2018',
        link: 'https://meileaf.com/tea/green-coil-tea/',
        brewing: {
            western: {
                temperature: 80,
                amount: 0.5,
                baseDuration: 120,
                durationIncrease: 60,
                infusions: 2,
            },
            gongfu: {
                temperature: 80,
                amount: 3.5,
                baseDuration: 15,
                durationIncrease: 5,
                infusions: 5,
            },
        },
    },
    {
        type: 3,
        organic: false,
        color: '#af4a02',
        name: 'Amber Gaba',
        nameOther: false,
        season: 'Spring 2016',
        cultivar: 'Chin Xin',
        origin: 'Alishan, Chiayi, Taiwan',
        rating: 3,
        updated: '14/01/2018',
        link: 'https://meileaf.com/tea/amber-gaba-oolong/',
        brewing: {
            western: {
                temperature: 99,
                amount: 1,
                baseDuration: 120,
                durationIncrease: 30,
                infusions: 3,
            },
            gongfu: {
                temperature: 99,
                amount: 5,
                baseDuration: 25,
                durationIncrease: 5,
                infusions: 9,
            },
        },
    },
    {
        type: 1,
        organic: false,
        color: '#dade68',
        name: 'Yellow Mountain Fur Peak',
        nameOther: 'Huang Shan Mao Feng',
        season: '23rd April 2017',
        cultivar: false,
        origin: 'Xiuning, Anhui, China',
        rating: 5,
        updated: '15/01/2018',
        link: 'https://www.teavivre.com/organic-huang-shan-mao-feng-green-tea.html',
        brewing: {
            western: {
                temperature: 85,
                amount: 1,
                baseDuration: 180,
                durationIncrease: 60,
                infusions: 2,
            },
            gongfu: {
                temperature: 85,
                amount: 3.5,
                baseDuration: 30,
                durationIncrease: 30,
                infusions: 4,
            },
        },
    },
    {
        type: 7,
        organic: false,
        color: '#cdd22c',
        name: 'Fireweed Tea',
        nameOther: 'Ivan Chai',
        season: false,
        cultivar: 'Chamaenerion Angustifolium',
        origin: 'Russia',
        rating: 4,
        updated: '17/01/2018',
        lnik: false,
        brewing: {
            western: {
                temperature: 90,
                amount: 3,
                baseDuration: 180,
                durationIncrease: 120,
                infusions: 3,
            },
        },
    },
    {
        type: 1,
        organic: false,
        color: '#b4b84b',
        name: 'Uji Genmai Matcha',
        nameOther: false,
        season: false,
        cultivar: false,
        origin: 'Uji, Kyoto, Japan',
        rating: 1,
        updated: '19/01/2018',
        link: false,
        brewing: {
            western: {
                temperature: 80,
                amount: 1,
                baseDuration: 120,
                durationIncrease: 30,
                infusions: 2,
            },
            gongfu: {
                temperature: 80,
                amount: 5,
                baseDuration: 15,
                durationIncrease: 10,
                infusions: 5,
            },
        },
    },
];